const constants = {
	ADD_ROUTE: "ADD_ROUTE",
	REMOVE_ROUTE: "REMOVE_ROUTE",
	ADD_SPOT: "ADD_SPOT",
	REMOVE_SPOT: "REMOVE_SPOT",
	EDIT_SPOT: "EDIT_SPOT",
	FETCH_ROUTE: "FETCH_ROUTE",
	FETCH_ROUTES: "FETCH_ROUTES"
}

export default constants